################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../test/aborttest.c \
../test/afalgtest.c \
../test/asn1_encode_test.c \
../test/asn1_internal_test.c \
../test/asn1_string_table_test.c \
../test/asn1_time_test.c \
../test/asynciotest.c \
../test/asynctest.c \
../test/bad_dtls_test.c \
../test/bftest.c \
../test/bio_callback_test.c \
../test/bio_enc_test.c \
../test/bioprinttest.c \
../test/bntest.c \
../test/casttest.c \
../test/chacha_internal_test.c \
../test/cipher_overhead_test.c \
../test/cipherbytes_test.c \
../test/cipherlist_test.c \
../test/ciphername_test.c \
../test/clienthellotest.c \
../test/conf_include_test.c \
../test/constant_time_test.c \
../test/crltest.c \
../test/ct_test.c \
../test/ctype_internal_test.c \
../test/curve448_internal_test.c \
../test/d2i_test.c \
../test/danetest.c \
../test/destest.c \
../test/dhtest.c \
../test/drbg_cavs_data.c \
../test/drbg_cavs_test.c \
../test/drbgtest.c \
../test/dsatest.c \
../test/dtls_mtu_test.c \
../test/dtlstest.c \
../test/dtlsv1listentest.c \
../test/ecdsatest.c \
../test/ecstresstest.c \
../test/ectest.c \
../test/enginetest.c \
../test/evp_extra_test.c \
../test/evp_test.c \
../test/exdatatest.c \
../test/exptest.c \
../test/fatalerrtest.c \
../test/gmdifftest.c \
../test/handshake_helper.c \
../test/hmactest.c \
../test/ideatest.c \
../test/igetest.c \
../test/lhash_test.c \
../test/md2test.c \
../test/mdc2_internal_test.c \
../test/mdc2test.c \
../test/memleaktest.c \
../test/modes_internal_test.c \
../test/ocspapitest.c \
../test/packettest.c \
../test/pbelutest.c \
../test/pemtest.c \
../test/pkey_meth_kdf_test.c \
../test/pkey_meth_test.c \
../test/poly1305_internal_test.c \
../test/rc2test.c \
../test/rc4test.c \
../test/rc5test.c \
../test/rdrand_sanitytest.c \
../test/recordlentest.c \
../test/rsa_mp_test.c \
../test/rsa_test.c \
../test/sanitytest.c \
../test/secmemtest.c \
../test/servername_test.c \
../test/shlibloadtest.c \
../test/siphash_internal_test.c \
../test/sm2crypttest.c \
../test/sm2sigtest.c \
../test/sm4_internal_test.c \
../test/srptest.c \
../test/ssl_cert_table_internal_test.c \
../test/ssl_test.c \
../test/ssl_test_ctx.c \
../test/ssl_test_ctx_test.c \
../test/sslapitest.c \
../test/sslbuffertest.c \
../test/sslcorrupttest.c \
../test/ssltest_old.c \
../test/ssltestlib.c \
../test/stack_test.c \
../test/sysdefaulttest.c \
../test/test_test.c \
../test/threadstest.c \
../test/time_offset_test.c \
../test/tls13ccstest.c \
../test/tls13encryptiontest.c \
../test/tls13secretstest.c \
../test/uitest.c \
../test/v3ext.c \
../test/v3nametest.c \
../test/verify_extra_test.c \
../test/versions.c \
../test/wpackettest.c \
../test/x509_check_cert_pkey_test.c \
../test/x509_dup_cert_test.c \
../test/x509_internal_test.c \
../test/x509_time_test.c \
../test/x509aux.c 

OBJS += \
./test/aborttest.o \
./test/afalgtest.o \
./test/asn1_encode_test.o \
./test/asn1_internal_test.o \
./test/asn1_string_table_test.o \
./test/asn1_time_test.o \
./test/asynciotest.o \
./test/asynctest.o \
./test/bad_dtls_test.o \
./test/bftest.o \
./test/bio_callback_test.o \
./test/bio_enc_test.o \
./test/bioprinttest.o \
./test/bntest.o \
./test/casttest.o \
./test/chacha_internal_test.o \
./test/cipher_overhead_test.o \
./test/cipherbytes_test.o \
./test/cipherlist_test.o \
./test/ciphername_test.o \
./test/clienthellotest.o \
./test/conf_include_test.o \
./test/constant_time_test.o \
./test/crltest.o \
./test/ct_test.o \
./test/ctype_internal_test.o \
./test/curve448_internal_test.o \
./test/d2i_test.o \
./test/danetest.o \
./test/destest.o \
./test/dhtest.o \
./test/drbg_cavs_data.o \
./test/drbg_cavs_test.o \
./test/drbgtest.o \
./test/dsatest.o \
./test/dtls_mtu_test.o \
./test/dtlstest.o \
./test/dtlsv1listentest.o \
./test/ecdsatest.o \
./test/ecstresstest.o \
./test/ectest.o \
./test/enginetest.o \
./test/evp_extra_test.o \
./test/evp_test.o \
./test/exdatatest.o \
./test/exptest.o \
./test/fatalerrtest.o \
./test/gmdifftest.o \
./test/handshake_helper.o \
./test/hmactest.o \
./test/ideatest.o \
./test/igetest.o \
./test/lhash_test.o \
./test/md2test.o \
./test/mdc2_internal_test.o \
./test/mdc2test.o \
./test/memleaktest.o \
./test/modes_internal_test.o \
./test/ocspapitest.o \
./test/packettest.o \
./test/pbelutest.o \
./test/pemtest.o \
./test/pkey_meth_kdf_test.o \
./test/pkey_meth_test.o \
./test/poly1305_internal_test.o \
./test/rc2test.o \
./test/rc4test.o \
./test/rc5test.o \
./test/rdrand_sanitytest.o \
./test/recordlentest.o \
./test/rsa_mp_test.o \
./test/rsa_test.o \
./test/sanitytest.o \
./test/secmemtest.o \
./test/servername_test.o \
./test/shlibloadtest.o \
./test/siphash_internal_test.o \
./test/sm2crypttest.o \
./test/sm2sigtest.o \
./test/sm4_internal_test.o \
./test/srptest.o \
./test/ssl_cert_table_internal_test.o \
./test/ssl_test.o \
./test/ssl_test_ctx.o \
./test/ssl_test_ctx_test.o \
./test/sslapitest.o \
./test/sslbuffertest.o \
./test/sslcorrupttest.o \
./test/ssltest_old.o \
./test/ssltestlib.o \
./test/stack_test.o \
./test/sysdefaulttest.o \
./test/test_test.o \
./test/threadstest.o \
./test/time_offset_test.o \
./test/tls13ccstest.o \
./test/tls13encryptiontest.o \
./test/tls13secretstest.o \
./test/uitest.o \
./test/v3ext.o \
./test/v3nametest.o \
./test/verify_extra_test.o \
./test/versions.o \
./test/wpackettest.o \
./test/x509_check_cert_pkey_test.o \
./test/x509_dup_cert_test.o \
./test/x509_internal_test.o \
./test/x509_time_test.o \
./test/x509aux.o 

C_DEPS += \
./test/aborttest.d \
./test/afalgtest.d \
./test/asn1_encode_test.d \
./test/asn1_internal_test.d \
./test/asn1_string_table_test.d \
./test/asn1_time_test.d \
./test/asynciotest.d \
./test/asynctest.d \
./test/bad_dtls_test.d \
./test/bftest.d \
./test/bio_callback_test.d \
./test/bio_enc_test.d \
./test/bioprinttest.d \
./test/bntest.d \
./test/casttest.d \
./test/chacha_internal_test.d \
./test/cipher_overhead_test.d \
./test/cipherbytes_test.d \
./test/cipherlist_test.d \
./test/ciphername_test.d \
./test/clienthellotest.d \
./test/conf_include_test.d \
./test/constant_time_test.d \
./test/crltest.d \
./test/ct_test.d \
./test/ctype_internal_test.d \
./test/curve448_internal_test.d \
./test/d2i_test.d \
./test/danetest.d \
./test/destest.d \
./test/dhtest.d \
./test/drbg_cavs_data.d \
./test/drbg_cavs_test.d \
./test/drbgtest.d \
./test/dsatest.d \
./test/dtls_mtu_test.d \
./test/dtlstest.d \
./test/dtlsv1listentest.d \
./test/ecdsatest.d \
./test/ecstresstest.d \
./test/ectest.d \
./test/enginetest.d \
./test/evp_extra_test.d \
./test/evp_test.d \
./test/exdatatest.d \
./test/exptest.d \
./test/fatalerrtest.d \
./test/gmdifftest.d \
./test/handshake_helper.d \
./test/hmactest.d \
./test/ideatest.d \
./test/igetest.d \
./test/lhash_test.d \
./test/md2test.d \
./test/mdc2_internal_test.d \
./test/mdc2test.d \
./test/memleaktest.d \
./test/modes_internal_test.d \
./test/ocspapitest.d \
./test/packettest.d \
./test/pbelutest.d \
./test/pemtest.d \
./test/pkey_meth_kdf_test.d \
./test/pkey_meth_test.d \
./test/poly1305_internal_test.d \
./test/rc2test.d \
./test/rc4test.d \
./test/rc5test.d \
./test/rdrand_sanitytest.d \
./test/recordlentest.d \
./test/rsa_mp_test.d \
./test/rsa_test.d \
./test/sanitytest.d \
./test/secmemtest.d \
./test/servername_test.d \
./test/shlibloadtest.d \
./test/siphash_internal_test.d \
./test/sm2crypttest.d \
./test/sm2sigtest.d \
./test/sm4_internal_test.d \
./test/srptest.d \
./test/ssl_cert_table_internal_test.d \
./test/ssl_test.d \
./test/ssl_test_ctx.d \
./test/ssl_test_ctx_test.d \
./test/sslapitest.d \
./test/sslbuffertest.d \
./test/sslcorrupttest.d \
./test/ssltest_old.d \
./test/ssltestlib.d \
./test/stack_test.d \
./test/sysdefaulttest.d \
./test/test_test.d \
./test/threadstest.d \
./test/time_offset_test.d \
./test/tls13ccstest.d \
./test/tls13encryptiontest.d \
./test/tls13secretstest.d \
./test/uitest.d \
./test/v3ext.d \
./test/v3nametest.d \
./test/verify_extra_test.d \
./test/versions.d \
./test/wpackettest.d \
./test/x509_check_cert_pkey_test.d \
./test/x509_dup_cert_test.d \
./test/x509_internal_test.d \
./test/x509_time_test.d \
./test/x509aux.d 


# Each subdirectory must supply rules for building sources it contributes
test/%.o: ../test/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


